spring:
    application:
       name: ecommerce-couchbase
server:
  port: 8761
couchbase:
    connection:
      host: localhost
      userName: couchbase
      password: couchbase
    bucket:
     product: product
     customer: customers
     reviews: reviews
     purchases: purchases